name: observability-ci

on:
  pull_request:
    branches:
    - develop
    - master
  push:
    branches:
    - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 5.0.x

      - name: Install Prerequisites
        run: sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb

      - name: Restore dependencies
        run: dotnet restore aspnetrun-microservices.sln

      - name: Build
        run: dotnet build --no-restore aspnetrun-microservices.sln

      - name: Test
        run: dotnet test aspnetrun-microservices.sln
